FROM node:alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD docker-resources /docker-resources

RUN /docker-resources/build-dev.sh

CMD [ "forever", "-w", "start", "npm", "--", "run", "dev" ]
