---
version: '3.0'

services:
  node:
    build: .
    volumes:
      - "./app/:/usr/src/app/"
    ports:
      - "${DOCKERPORT}:4321"

# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    name: ${DOCKERNETWORK}
    external: true

# volumes:
#   mongo:
