# This can be used for API keys or anything which differs from one
# environment to another.
---
version: 2
modules:
  someModule: {
    'super-secret-api-key': 'princess',
  }
  # You could have something like this in production if you want to use a
  # real mail server instead of MailHog, the default for development.
  mail:
    defaultServer:
      name: myServer
      service: smtp
  smtp:
    servers:
      myServer:
        host: smtp.sendgrid.net
        port: 465
        secure: true
        user: apikey
        pass: SUPER-SECRET-SENDGRID-API-KEY
