---
version: 2
services:
  webAuth:
  rolesAndPermissions:
    roles:
      administrator:
        permissions: all
  chatApi:
    path:
      canonical: 'messages'
      access:
        service: webAuth
        parameters:
          authenticated: true
  chatWeb:
    path:
      canonical: '/'
      access:
        service: webAuth
        parameters:
          authenticated: true
  userPassAuth: {}
  # This can be overridden in unversioned.yml, as per the example in
  # ./app/config/unversioned.example.yml.
  mail:
    defaultServer:
      name: mailhog
      service: './smtp/index.js'
  smtp:
    servers:
      mailhog:
        host: mail
        port: 1025
        secure: false
        user: ""
        pass: ""
  numUsers: {}
  repl:
    port: 8001
  express:
    port: 8080
  staticPath:
    paths:
      - /usr/src/app/static
  dashboardApi: {}
  dashboardWeb:
    path:
      canonical: '/admin/dashboard'
      access:
        service: rolesAndPermissions
        parameters:
          permissions:
            operator: all
            permission: 'view dashboard'
