---
modules:
  ./webAuth/index.js:
    authenticated:
      - route: chat
        verb: get
      - route: chatApi
        verb: get
      - route: chatApi
        verb: post
      - route: CrashTest
        verb: get
      - route: accountFrameworkUserDetail
        verb: get
      - route: accountFrameworkMerge
        verb: post
      - route: accountFrameworkUnMerge
        verb: post
      - route: accountFrameworkMergeUI
        verb: get
      - route: accountFrameworkMergeUIGT
        verb: get
      - route: accountFrameworkTokenSubmit
        verb: post
      - route: accountFrameworkUnmergeSubmit
        verb: get
      - route: viewStripeSubscriptionsList
        verb: get
      - route: addSubscription
        verb: get
      - route: createSubscription
        verb: post
      - route: cancelSubscription
        verb: post
      - route: addPaymentMethod
        verb: post
      - route: addPaymentMethod
        verb: get
    authenticatedJson:
      - route: tokenRequest
        verb: get
    anonymous:
      - route: tokenCheck
        verb: get
      - route: rest
        verb: get
      - route: webhookWhatsApp
        verb: post
      - route: whatsappSend
        verb: post
      - route: sendSMS
        verb: post
      - route: webhookSMS
        verb: post
      - route: googleErr
        verb: get
      - route: textFrameworkPlugins
        verb: get
  ./rest/index.js:
    path: '/api/v1'
  ./chatWeb/index.js:
    path: '/'
  ./userPassAuth/index.js: {}
  ./userPhoneNumberAuth/index.js:
    tokenExpiryDuration: 3
  # This can be overridden in unversioned.yml, as per the example in
  # ./app/config/unversioned.example.yml.
  ./mail/index.js:
    defaultServer:
      name: mailhog
      component: './smtp/index.js'
  ./smtp/index.js:
    servers:
      mailhog:
        host: mail
        port: 1025
        secure: false
        user: ""
        pass: ""
  ./numUsers/index.js: {}
  ./loginWithGitHub/index.js:
    client: 'override this in ./app/config/unversioned.yml; see README.md'
    secret: 'override this in ./app/config/unversioned.yml; see README.md'
    baseUrl: 'override this in ./app/config/unversioned.yml; see README.md'
    callback: '/auth/github/callback'
  ./loginWithGoogle/index.js:
    client: 'override this in ./app/config/unversioned.yml; see README.md'
    secret: 'override this in ./app/config/unversioned.yml; see README.md'
    baseUrl: 'override this in ./app/config/unversioned.yml; see README.md'
    callback: '/auth/google/callback'
  ./restrictedByPermission/index.js:
    restrictedfolderpath:
      - /usr/src/app/private/restricted-by-permission/
  ./repl/index.js:
    port: 8001
  ./express/index.js:
    port: 8080
  ./staticPath/index.js:
    paths:
      - /usr/src/app/static
  ./crashTest/index.js: {}
  ./chatbot/index.js:
    plugins:
      calculator:
        name: calculator
        plugin: chatbotCalculator
  ./chatbotCalculator/index.js: {}
  ./textFramework/index.js:
    plugins:
      whatsapp:
        name: whatsapp
        plugin: textFrameworkWhatsApp
        requiredParams:
          - 'sendTo'
          - 'message'
      sms:
        name: sms
        plugin: textFrameworkSMS
        requiredParams:
          - 'sendTo'
          - 'message'
      internal:
        name: internal
        plugin: textFrameworkInternal
        requiredParams:
          - 'name'
          - 'message'
  ./textFrameworkWhatsApp/index.js: {}
  ./textFrameworkSMS/index.js: {}
  ./textFrameworkInternal/index.js: {}
  ./dashboardApi/index.js: {}
  ./observer/index.js: {}
  ./observerExamplePublisher/index.js: {}
  ./observerExampleSubscriber/index.js: {}
  ./whatsAppSend/index.js: {}
  ./webhookWhatsApp/index.js: {}
  ./webhookWhatsAppSubscriber/index.js: {}
  ./sendSMS/index.js: {}
  ./webhookSMS/index.js: {}
  ./helpers/index.js: {}
  ./tokens/index.js: {}
  ./accountFramework/index.js:
    # Token expiry duration 1 hour = 3600 seconds
    tokenExpiryDuration: 3600
  ./stripeSubscriptions/index.js:
    stripeSecurityKey: 'override this in ./app/config/unversioned.yml; see README.md'
    stripePublishableKey: 'override this in ./app/config/unversioned.yml; see README.md'
