---
modules:
  ./webAuth/index.js:
    authenticated:
      - chat
  ./chatWeb/index.js: {}
  ./userPassAuth/index.js: {}
  ./numUsers/index.js: {}
  ./repl/index.js:
    port: 8001
  ./express/index.js:
    port: 8080
  ./staticPath/index.js:
    paths:
      - /usr/src/app/static
