---
modules:
  ./webAuth/index.js:
    roles:
      authenticated:
        - "view authenticated routes"
        - "view chat"
        - "view chatApi"
        - "create chatApi message"
        - "send chatApi message"
        - "perform crash test"
        - "view user details"
        - "merge accounts"
        - "unmerge accounts"
        - "view merge UI"
        - "view merge UI (GT)"
        - "submit token"
        - "submit unmerge request"
        - "view Stripe subscriptions"
        - "add subscription"
        - "create subscription"
        - "cancel subscription"
        - "add payment method"
        - "view payment method"
        - "request json token"

      administrator:
        - "*"

      anonymous:
        - "view public routes"
        - "check token status"
        - "access REST endpoints"
        - "receive WhatsApp webhook"
        - "send WhatsApp message"
        - "send SMS"
        - "receive SMS webhook"
        - "view Google error logs"
        - "view text framework plugins"

    routes:
      # Authenticated Routes
      - route: chat
        verb: get
        permission: "view chat"
      - route: chatApi
        verb: get
        permission: "view chatApi"
      - route: chatApi
        verb: post
        permission: "create chatApi message"
      - route: chatApi
        verb: post
        permission: "send chatApi message"
      - route: CrashTest
        verb: get
        permission: "perform crash test"
      - route: accountFrameworkUserDetail
        verb: get
        permission: "view user details"
      - route: accountFrameworkMerge
        verb: post
        permission: "merge accounts"
      - route: accountFrameworkUnMerge
        verb: post
        permission: "unmerge accounts"
      - route: accountFrameworkMergeUI
        verb: get
        permission: "view merge UI"
      - route: accountFrameworkMergeUIGT
        verb: get
        permission: "view merge UI (GT)"
      - route: accountFrameworkTokenSubmit
        verb: post
        permission: "submit token"
      - route: accountFrameworkUnmergeSubmit
        verb: get
        permission: "submit unmerge request"
      - route: viewStripeSubscriptionsList
        verb: get
        permission: "view Stripe subscriptions"
      - route: addSubscription
        verb: get
        permission: "add subscription"
      - route: createSubscription
        verb: post
        permission: "create subscription"
      - route: cancelSubscription
        verb: post
        permission: "cancel subscription"
      - route: addPaymentMethod
        verb: post
        permission: "add payment method"
      - route: addPaymentMethod
        verb: get
        permission: "view payment method"
      - route: dashboardUI
        verb: get
        permission: "view dashboard UI"

      # AuthenticatedJson Route
      - route: tokenRequest
        verb: get
        permission: "request json token"

      # Anonymous Route
      - route: tokenCheck
        verb: get
        permission: "check token status"
      - route: rest
        verb: get
        permission: "access REST endpoints"
      - route: webhookWhatsApp
        verb: post
        permission: "receive WhatsApp webhook"
      - route: whatsappSend
        verb: post
        permission: "send WhatsApp message"
      - route: sendSMS
        verb: post
        permission: "send SMS"
      - route: webhookSMS
        verb: post
        permission: "receive SMS webhook"
      - route: googleErr
        verb: get
        permission: "view Google error logs"
      - route: textFrameworkPlugins
        verb: get
        permission: "view text framework plugins"

  ./rest/index.js:
    path: '/api/v1'
  ./chatWeb/index.js:
    path: '/'
  ./userPassAuth/index.js: {}
  ./userPhoneNumberAuth/index.js:
    tokenExpiryDuration: 3
  # This can be overridden in unversioned.yml, as per the example in
  # ./app/config/unversioned.example.yml.
  ./mail/index.js:
    defaultServer:
      name: mailhog
      component: './smtp/index.js'
  ./smtp/index.js:
    servers:
      mailhog:
        host: mail
        port: 1025
        secure: false
        user: ""
        pass: ""
  ./numUsers/index.js: {}
  ./loginWithGitHub/index.js:
    client: 'override this in ./app/config/unversioned.yml; see README.md'
    secret: 'override this in ./app/config/unversioned.yml; see README.md'
    baseUrl: 'override this in ./app/config/unversioned.yml; see README.md'
    callback: '/auth/github/callback'
  ./loginWithGoogle/index.js:
    client: 'override this in ./app/config/unversioned.yml; see README.md'
    secret: 'override this in ./app/config/unversioned.yml; see README.md'
    baseUrl: 'override this in ./app/config/unversioned.yml; see README.md'
    callback: '/auth/google/callback'
  ./restrictedByPermission/index.js:
    restrictedfolderpath:
      - /usr/src/app/private/restricted-by-permission/
  ./repl/index.js:
    port: 8001
  ./express/index.js:
    port: 8080
  ./staticPath/index.js:
    paths:
      - /usr/src/app/static
  ./crashTest/index.js: {}
  ./chatbot/index.js:
    plugins:
      calculator:
        name: calculator
        plugin: chatbotCalculator
  ./chatbotCalculator/index.js: {}
  ./textFramework/index.js:
    plugins:
      whatsapp:
        name: whatsapp
        plugin: textFrameworkWhatsApp
        requiredParams:
          - 'sendTo'
          - 'message'
      sms:
        name: sms
        plugin: textFrameworkSMS
        requiredParams:
          - 'sendTo'
          - 'message'
      internal:
        name: internal
        plugin: textFrameworkInternal
        requiredParams:
          - 'name'
          - 'message'
  ./textFrameworkWhatsApp/index.js: {}
  ./textFrameworkSMS/index.js: {}
  ./textFrameworkInternal/index.js: {}
  ./dashboardApi/index.js: {}
  ./observer/index.js: {}
  ./observerExamplePublisher/index.js: {}
  ./observerExampleSubscriber/index.js: {}
  ./whatsAppSend/index.js: {}
  ./webhookWhatsApp/index.js: {}
  ./webhookWhatsAppSubscriber/index.js: {}
  ./sendSMS/index.js: {}
  ./webhookSMS/index.js: {}
  ./helpers/index.js: {}
  ./tokens/index.js: {}
  ./accountFramework/index.js:
    # Token expiry duration 1 hour = 3600 seconds
    tokenExpiryDuration: 3600
  ./stripeSubscriptions/index.js:
    stripeSecurityKey: 'override this in ./app/config/unversioned.yml'
    stripePublishableKey: 'override this in ./app/config/unversioned.yml'
  ./dashboardUI/index.js: {}
