---
modules:
  ./webAuth/index.js:
    authenticated:
      - route: chat
        verb: get
      - route: chatApi
        verb: get
      - route: chatApi
        verb: post
  ./chatWeb/index.js:
    path: '/'
  ./userPassAuth/index.js: {}
  ./numUsers/index.js: {}
  ./repl/index.js:
    port: 8001
  ./express/index.js:
    port: 8080
  ./staticPath/index.js:
    paths:
      - /usr/src/app/static
