---
modules:
  ./webAuth/index.js:
    authenticated:
      - route: chat
        verb: get
      - route: chatApi
        verb: get
      - route: chatApi
        verb: post
  ./chatWeb/index.js:
    path: '/'
  ./userPassAuth/index.js: {}
  # This can be overridden in unversioned.yml, as per the example in
  # ./app/config/unversioned.example.yml.
  ./mail/index.js:
    defaultServer:
      name: mailhog
      component: './smtp/index.js'
  ./smtp/index.js:
    servers:
      mailhog:
        host: mail
        port: 1025
        secure: false
        user: ""
        pass: ""
  ./numUsers/index.js: {}
  ./repl/index.js:
    port: 8001
  ./express/index.js:
    port: 8080
  ./staticPath/index.js:
    paths:
      - /usr/src/app/static
  ./dashboardApi/index.js: {}
