---
modules:
  ./webAuth/index.js:
    authenticated:
      - route: chat
        verb: get
      - route: chatApi
        verb: get
      - route: chatApi
        verb: post
      - route: CrashTest
        verb: get
    authenticatedJson:
      - route: tokenRequest
        verb: get
    anonymous:
      - route: tokenCheck
        verb: get
      - route: rest
        verb: get
      - route: webhookWhatsApp
        verb: post
      - route: whatsappSend
        verb: post
      - route: sendSMS
        verb: post
      - route: webhookSMS
        verb: post
      - route: googleErr
        verb: get
  ./rest/index.js:
    path: '/api/v1'
  ./chatWeb/index.js:
    path: '/'
  ./userPassAuth/index.js: {}
  # This can be overridden in unversioned.yml, as per the example in
  # ./app/config/unversioned.example.yml.
  ./mail/index.js:
    defaultServer:
      name: mailhog
      component: './smtp/index.js'
  ./smtp/index.js:
    servers:
      mailhog:
        host: mail
        port: 1025
        secure: false
        user: ""
        pass: ""
  ./numUsers/index.js: {}
  ./loginWithGitHub/index.js:
    client: 'override this in ./app/config/unversioned.yml; see README.md'
    secret: 'override this in ./app/config/unversioned.yml; see README.md'
    baseUrl: 'override this in ./app/config/unversioned.yml; see README.md'
    callback: '/auth/github/callback'
  ./loginWithGoogle/index.js:
    client: 'override this in ./app/config/unversioned.yml; see README.md'
    secret: 'override this in ./app/config/unversioned.yml; see README.md'
    baseUrl: 'override this in ./app/config/unversioned.yml; see README.md'
    callback: '/auth/google/callback'
  ./restrictedByPermission/index.js:
    restrictedfolderpath:
      - /usr/src/app/private/restricted-by-permission/
  ./repl/index.js:
    port: 8001
  ./express/index.js:
    port: 8080
  ./staticPath/index.js:
    paths:
      - /usr/src/app/static
  ./crashTest/index.js: {}
  ./chatbot/index.js:
    plugins:
      calculator:
        name: calculator
        plugin: chatbotCalculator
  ./chatbotCalculator/index.js: {}
  ./dashboardApi/index.js: {}
  ./webhookWhatsApp/index.js: {}
  ./whatsAppSend/index.js: {}
  ./sendSMS/index.js: {}
